# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java package with Gradle

on:
  workflow_dispatch:
    inputs:
      ssh:
        description: "SSH connection to Actions"
        required: false
        default: "false"

jobs:
  job1:
    name: build for linux
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17 for
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Build with Gradle
        uses: gradle/gradle-build-action@937999e9cc2425eddc7fd62d1053baf041147db7
        with:
          arguments: build
      - name: package with Gradle
        uses: gradle/gradle-build-action@937999e9cc2425eddc7fd62d1053baf041147db7
        with:
          arguments: package
      - name: Upload math result linux
        uses: actions/upload-artifact@v2
        with:
          name: bookmark-deb
          path: build/compose/binaries/main/deb
  job2:
    name: build for windows
    needs:
      - job1
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17 for
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Build with Gradle
        uses: gradle/gradle-build-action@937999e9cc2425eddc7fd62d1053baf041147db7
        with:
          arguments: build
      - name: package with Gradle
        uses: gradle/gradle-build-action@937999e9cc2425eddc7fd62d1053baf041147db7
        with:
          arguments: package
      - name: Upload math result windows
        uses: actions/upload-artifact@v2
        with:
          name: bookmark-win
          path: build/compose/binaries/main/msi
  job3:
    name: build for macos
    needs:
      - job2
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17 for
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Build with Gradle
        uses: gradle/gradle-build-action@937999e9cc2425eddc7fd62d1053baf041147db7
        with:
          arguments: build
      - name: package with Gradle
        uses: gradle/gradle-build-action@937999e9cc2425eddc7fd62d1053baf041147db7
        with:
          arguments: package
      - name: Upload math result macos
        uses: actions/upload-artifact@v2
        with:
          name: bookmark-macos
          path: build/compose/binaries/main/dmg
  job4:
    name: release
    needs:
      - job1
      - job2
      - job3
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: download the latest version of the project
        uses: actions/download-artifact@v2
        with:
          name: bookmark-deb
          path: up/
      - name: download the latest version of the project
        uses: actions/download-artifact@v2
        with:
          name: bookmark-win
          path: up/
      - name: download the latest version of the project
        uses: actions/download-artifact@v2
        with:
          name: bookmark-macos
          path: up/
      - name: Generate release tag
        id: release-tag
        shell: bash
        run: |
          echo "::set-output name=release_tag::v$(date +%Y%m%d%H%M%S)" 
          echo "使用github actions的打包、并发布构建好的安装包" > release.txt
      - name: release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.tag.outputs.release_tag }}
          body_path: release.txt
          files: up/*
